site_name: torchcnnbuilder-doc

nav:
  - Main: index.md
  - API:
    - "torchcnnbuilder": api/torchcnnbuilder.md
    - "torchcnnbuilder.builder": api/torchcnnbuilder-builder.md
    - "torchcnnbuilder.latent": api/torchcnnbuilder-latent.md
    - "torchcnnbuilder.models": api/torchcnnbuilder-models.md
  - Contribution:
    - "Development guide": contribution/development-guide.md
    - "Doc guide": contribution/doc-guide.md

theme:
  name: ivory

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


