name: Build Doc

on: [push]


jobs:
  build-docs:
    name: Build torchcnnbuilder documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc3

      - name: Remove old documentation
        run: rm -rf docs/*.html

      - name: Build documentation
        run: |
          pdoc --output-dir docs --html torchcnnbuilder --config latex_math=True
          mv docs/torchcnnbuilder/* docs/
          rm -rf docs/torchcnnbuilder

      - name: List documentation files
        run: ls -R docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
